---
title:               George Shank
tagline:             Superman does good. I'm doing well.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                George Shank
twitter:             georgeshank
github:              shankga
email:               shankga@gmail.com
#google_analytics_id: YOUR_GA_ID